# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'ClarifaiAPITest' do

pod ' BDBOAuth1Manager '

end

target 'ClarifaiAPITestTests' do

end

target 'ClarifaiAPITestUITests' do

end

